name: check

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main, master]

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    container:
      image: ghcr.io/pik-piam/ci-image:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        shell: Rscript {0}
        run: |
          options(repos = c(pikpiam = 'https://pik-piam.r-universe.dev',
                            CRAN = Sys.getenv('RSPM')))
          pak::pak()
          
      - name: Run pre-commit checks
        shell: bash
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Verify validation key
        shell: Rscript {0}
        run: lucode2:::validkey(stopIfInvalid = TRUE)

      - name: Verify that lucode2::buildLibrary was successful
        if: github.event_name == 'pull_request'
        shell: Rscript {0}
        run: lucode2:::isVersionUpdated()

      - name: Checks
        shell: Rscript {0}
        run: |
          options(crayon.enabled = TRUE)
          lucode2::check(runLinter = FALSE)

      - name: Test coverage
        if: ${{ github.event_name != 'pull_request' }}
        shell: Rscript {0}
        run: |
          nonDummyTests <- setdiff(list.files("./tests/testthat/"), c("test-dummy.R", "_snaps"))
          if(length(nonDummyTests) > 0 && !lucode2:::loadBuildLibraryConfig()[["skipCoverage"]]) {
            coverage <- covr::package_coverage(quiet = FALSE)
            # The following function might be unnecessary if r-lib/covr#616 gets merged
            to_simple_codecov <- function(coverage) {
              fullLineCoverage <- covr:::per_line(coverage)
              data <- Map(function(fileCoverage) {
                resultCoverage <- lapply(fileCoverage$coverage, jsonlite::unbox)
                names(resultCoverage) <- seq_along(resultCoverage)
                return(resultCoverage)
              }, fullLineCoverage)
              return(jsonlite::toJSON(list("coverage" = data), na = "null"))
            }
            writeLines(to_simple_codecov(coverage), "simple-codecov.json")
          }
        env:
          NOT_CRAN: "true"

      - uses: codecov/codecov-action@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          file: ./simple-codecov.json
          plugin: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
